### ISSUE TITLE
Add support for url namespaces when attaching url_mptt to namespaced pattern

### ISSUE THREAD

**Issue by destos** [c0ntribut0r/django-mptt-urls#2]
I'm currently experimenting with using namespaces in django and noticed that there are errors when adding a namespace to a lower url pattern that the url_mptt gernerated url is attached to.

The failure occurs when the reverse is run inside the model bound get_absolute_url method, as the url is now namespaced it no longer works.
https://github.com/MrKesn/django-mptt-urls/blob/master/mptt_urls/__init__.py#L29

I'll be investigating if there is a way we can pass along namespacing information to get_absolute_url so the lookup can be done correctly.

**Comment by 3ka5-cat** [comment]
Hi,
is there any progress on this issue?

**Comment by c0ntribut0r** [comment]
@3ka5-cat The project is updated to 2.0.0a1 version (finally!). It has a whole new syntax, and internal mechanisms changed a lot. Now the code is as simple as possible, so perhaps this concrete issue is gone.

**Comment by 3ka5-cat** [comment]
Yeah, I've already mentioned this :) It's really more clean and clear now, thank you!
After some research, I found that my trouble wasn't coupled with urls namespace.

But, there is a trouble with PyPi still. Should I create separate issue for it?

**Comment by c0ntribut0r** [comment]
There's no trouble with PyPi. As soon as new version is alpha, pip won't install it unless you tell him to do it explicitly:
`pip install django-mptt-urls==2.0.0a1`
