### ISSUE TITLE
Not showing data for main categories

### ISSUE THREAD

**Issue by aditya-singh177** [c0ntribut0r/django-mptt-urls#5]
hello ...i followed django-mptt-urls....but i shows data only for the subcategory in which the photos are added but if we click on the category above it doesnt show any data...although it must show all the data present in together in all the below subcategories

for eg
men>menclothing>tshirts
men>menclothing>jeans

when clicking on menclothing it must show data for both tshirts and jeans combined

**Comment by c0ntribut0r** [comment]
@aditya-singh177 You are the king of your Django app, not django-mptt-urls.

Add special method to your Category class:
```
class Category(MPTTModel):
    # some stuff

    def get_clothes(self):
        # displays all items from all subcategories
        return Clothing.objects.filter(parent__in=self.get_descendants(include_self=True))
```

Then use it in your template (category.html):
```
{% for clothing in instance.get_clothes %}
    <li>{{ clothing.name }}</li>
{% empty %}
     <li>No items</li>
{% endfor %}
```

This issue is not related to `django-mptt-urls`.

**Comment by aditya-singh177** [comment]
thanks a lot contributor

**Comment by aditya-singh177** [comment]
There one more issue regarding the breadcrumbs...i can do for loop through the ancestors ..but the breadcrumbs end at some subcategory level ...what if i wanted to end the breadcrumb at product level (not any category )  of any subcategory

for eg:-men>menclothing>tshirt>nike black v neck tshirt(product level)

**Comment by c0ntribut0r** [comment]
@aditya-singh177 Sorry, I cannot write code for you. You should definitely spend some time on learning Django basics.

This issue is not related to `django-mptt-urls`.

**Comment by aditya-singh177** [comment]
ok thanks....
