### ISSUE TITLE
how can i access the urls as links?

### ISSUE THREAD

**Issue by adityasingh177** [c0ntribut0r/django-mptt-urls#7]
how can i access the urls as links?

http://best-photographer.com/gallery/weddings/Dexter-and-Rita/
http://best-photographer.com/gallery/my-pets/dogs/husky/

**Comment by c0ntribut0r** [comment]
Move your cursor over the link and press left mouse button

**Comment by adityasingh177** [comment]
these are static...cant they be made dynamic...like url 'categories'

**Comment by c0ntribut0r** [comment]
@adityasingh177 I absolutely totally don't understand what you're saying. If you want to get dynamic urls for any category instance, use `instance.get_absolute_url()`

**Comment by adityasingh177** [comment]
it doesnt work when i am calling the instance.get_absolute_url() from another page that is outside the mptt tree...

**Comment by c0ntribut0r** [comment]
You should provide code example.

**Comment by adityasingh177** [comment]
Another.html 
-----------------

Categories :- 
weddings > Dexter and Rita
My Pets > Dogs > Husky

<div class = ' col-sm-3'>
<ul>

<li><a href="#">weddings</a></li>
                <li><a href="#">Dexter and Rita</a></li>
  
<li><a href="#">Pets</a></li>
               <li><a href="#">Dogs</a></li>
                                <li><a href="#">Husky</a></li>

</ul>

 i am a beginner.
How can i give Links in "a hrefs " here....thanks in advance...

**Comment by c0ntribut0r** [comment]
From your views.py pass desired instances to your template, like this:
```python
def another_page(request):
    return render(
        request,
        'another.html',
        {'categories': Category.objects.all()}
    )
```

Then in another.html:
```html
{% for category in categories %}
    {{ category.get_absolute_url }}
{% endfor %}
```

Note that in your `models.py` file you need to set up `def get_absolute_url()` for your `Category` model, as described here https://github.com/c0ntribut0r/django-mptt-urls in section get_absolute_url().
