### ISSUE TITLE
Reverse for 'categories' with arguments '( path, instance)' and keyword arguments '{}' not found. 1 pattern(s) tried: ['category/(?P<path>.*)']

### ISSUE THREAD

**Issue by Adrafe-Rinzzler** [c0ntribut0r/django-mptt-urls#9]
a href="{% url 'categories' path instance %}?query={{query.value}}">{{ query.value }}</a>

why above error is coming when i am passing path and instance from the url ?

 i have included path and instance in the context from the view

path = instance.get_absolute_url()
instance = instance

**Comment by c0ntribut0r** [comment]
The error message is quite verbose: your url rule `'category/(?P<path>.*)'` receives only 1 keyword argument (`path`), so the tag should look like this
```html
{% url 'categories' path=path %}
```

By the way, you are doing something strange. Please read `django-mptt-urls` documentation again, especially
```python
class Category(MPTTModel):
    ...
    def get_absolute_url(self):
        return reverse('gallery', kwargs={'path': self.get_path()})
```
The better approach for your code is this
```html
<a href="{{ instance.get_absolute_url }}?query=...">
```

**Comment by Adrafe-Rinzzler** [comment]
thanks alex....i tried it ...but throws this error..'NoneType' object has no attribute 'get_descendants'

somehow the instance becomes none....

here is the view

def category(request, path, instance, extra):
    if instance:
        instance.save()

    queryset = Product.objects.filter(category__in=instance.get_descendants(include_self=True))

    color = request.GET.get('query')

    if query:
    	queryset = queryset.filter(optiongroup__color=query)
   
    return render(
        request,
        'products/prodgrid.html',
        {
            'instance': instance,
            'children': instance.get_children() if instance else Category.objects.root_nodes(),
            'extra': extra,
            'queryset': queryset
        }
    )

**Comment by c0ntribut0r** [comment]
Maybe this will help
```python
    queryset = Product.objects.filter(category__in=instance.get_descendants(include_self=True)) if instance else Product.objects.all()
```

**Comment by Adrafe-Rinzzler** [comment]
It won't as it shows all products if instance is none...why the instance is becoming none when sending the query?

**Comment by c0ntribut0r** [comment]
> If resolution fails, instance will be None.

So, probably the `?P<path>.*` part is empty (you open a 'root' page) or something is going wrong. If you're using v2.0.2 check whether your url end up with slash (ie /products/slug1/slug2**/**)

**Comment by Adrafe-Rinzzler** [comment]
No its not ending with that.....though I have given as u said in the link ...when I click on it ...reloads the page with no instance

**Comment by Adrafe-Rinzzler** [comment]
The resolution fails when I append that query string....wonder why?

**Comment by c0ntribut0r** [comment]
Insert this in your views.py and tell me the output:
```python
def category(request, path, instance, extra):
    print('Path: [{}]'.format(path))
    slug = path.split('/')[-2]
    print('Slug: [{}]'.format(slug))
    if slug:
        for candidate in Product.objects.filter(slug=slug):
            print('Candidate slug: [{}]'.format(candidate.slug))
   # ... your code following ...
```

**Comment by c0ntribut0r** [comment]
Ah, I think I got it...

**Comment by Adrafe-Rinzzler** [comment]
list index out of range

Traceback:
File "C:\Python27\lib\site-packages\django\core\handlers\base.py" in get_response
  132.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "C:\Users\lenovo\Desktop\plump\Plumpin\src\mptt_urls\__init__.py" in __call__
  35.         return self.view(*args, **kwargs)
File "C:\Users\lenovo\Desktop\plump\Plumpin\src\products\views.py" in category
  35.     slug = path.split('/')[-2]

Exception Type: IndexError at /category/women
Exception Value: list index out of range

**Comment by Adrafe-Rinzzler** [comment]
the resolution fails when 
category/women/?color=blue

**Comment by c0ntribut0r** [comment]
I've made some changes, try to update
116590e22a271e5609b4a1c3607af03dccade8ab

**Comment by Adrafe-Rinzzler** [comment]
OK Alex....just keep this issue open for sometime...if incase

**Comment by Adrafe-Rinzzler** [comment]
updated...what changes did u make?

**Comment by Adrafe-Rinzzler** [comment]
what happens when i m sending request to category function from another template ...say header.html
which has search box to query on category objects..
<form method = "GET" action = "{% url 'categories' path=path %} ">
				<input type= "text" name='q' style="height:45px; width:400px; padding:8px" value = '{{ request.Get.q }}'placeholder="Search"/>
				<button type="submit" class="btn btn-default" aria-label="Left Align" style="border-radius: 0px; background-color:#333333; width:50px; border-color:#333333; padding: 15px 12px; margin-top:1px;">
				  <span class="glyphicon glyphicon-search" aria-hidden="true" style="color:white;"></span>
				</button>
				</form>

**Comment by c0ntribut0r** [comment]
Time cures :)
